Repository 2023-WinterBootcamp-Team-M/frontend, pull requests merged in 2024-01, with the labels that each got.

#9 feat : 메뉴바 퍼블리싱
  src/Panel.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/setting/settingpage.tsx
  src/pages/start.tsx
Labels: 기능구현

#10 [feat/#7] 시작 페이지 퍼블리싱
  src/Panel.tsx
  src/index.html
  src/pages/start.tsx
Labels: 기능구현

#18 [feat/#8] 북마크 페이지 퍼블리싱
  src/Panel.tsx
  src/const.ts
  src/index.html
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 기능구현

#20 [feat/#19] 알림 페이지 퍼블리싱
  package.json
  src/index.html
  src/pages/alarm/alarmpage.tsx
  src/pages/alarm/notificationItem.tsx
  tailwind.config.js
Labels: 기능구현

#22 [feat/#16] 설정 페이지 및 클립보드 페이지 디자인 수정
  package.json
  src/Panel.tsx
  src/components/Button.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/pages/setting/darktheme.tsx
  src/pages/setting/settingpage.tsx
  yarn.lock
Labels: 디자인

#24 [feat/#21] 북마크 툴팁 기능 구현
  package.json
  src/components/ToolTip.tsx
  src/pages/bookmark/BookmarkPage.tsx
  yarn.lock
Labels: 기능구현

#27 [feat/#25] : 클립보드 페이지 툴팁 추가
  .vscode/settings.json
  src/pages/clipboard/clipboardpage.tsx
Labels: 기능구현

#29 [feat/#23] 로그인 및 회원 가입 창 퍼블리싱
  src/pages/start.tsx
Labels: 기능구현

#31 [feat/#30] 로그인 시 이메일 입력 초기화 수정
  src/pages/start.tsx
Labels: 기능구현

#32 [feat/#28] : Drag & Drop 기능구현
  package.json
  src/Panel.tsx
  src/components/DragNDrop.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
  yarn.lock
Labels: 기능구현

#35 [feat/#33] 클립보드 이미지 다운로드 기능 구현
  package.json
  src/Panel.tsx
  src/components/DragNDrop.tsx
  src/const.ts
  src/index.tsx
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/pages/start.tsx
  yarn.lock
Labels: 기능구현

#38 [feat/#36] 클립보드 API 연동
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 기능구현

#40 [feat/#37] 알림창 무한 스크롤 기능 구현
  package.json
  src/Panel.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/alarm/notificationItem.tsx
  yarn.lock
Labels: 기능구현

#41 [feat/#39] 클립보드 이미지 개별 삭제 기능구현
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 기능구현

#43 [issue/#42] : svg파일 path 속성 형식 수정
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 이슈해결

#47 [feat/#46] 유저의 폴더 조회, 수정, 삭제 API 연동
  src/pages/bookmark/BookmarkPage.tsx
Labels: 기능구현

#55 [Feat/#51] 설정 API 연동
  src/pages/setting/SettingAPI.tsx
  src/pages/setting/darktheme.tsx
  src/pages/setting/settingpage.tsx
  src/pages/start.tsx
  src/store/store.ts
Labels: 기능구현

#58 [issue] 엔드 포인트 수정
  src/pages/setting/SettingAPI.tsx
  src/pages/start.tsx
Labels: 이슈해결

#66 [feat/#63] 모달창 ui 수정
  src/components/ChangeProfileModal.tsx
  src/components/SigninModal.tsx
  src/components/SignupModal.tsx
  src/pages/setting/settingpage.tsx
Labels: 디자인, 기능구현

#68 [feat/#65] 폴더와 북마크 생성,삭제 기능과 즐겨찾기 및 요약 기능 구현
  src/components/DragNDrop.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/store/store.ts
Labels: 디자인, 기능구현

#71 [feat/#70] 클립보드 페이지 북마크 모달창 생성
  src/components/ClipBookmarkDropdown.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 기능구현

#72 [Issue/#69] 페이지 이동시 클립보드 삭제 현상 해결
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/store/store.ts
Labels: 이슈해결, 기능구현

#74 [feat/#73] 6줄,3줄요약 선택 기능 구현, 시작페이지 북마크or클립보드 선택 기능 구현
  src/components/DragNDrop.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/start.tsx
Labels: 기능구현

#79 [feat/#77] 알림 API 연동
  src/Panel.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/alarm/notificationItem.tsx
  src/pages/start.tsx
  src/store/store.ts
Labels: 기능구현

#81 [feat/#80] 북마크 폴더 자동분류 기능 구현
  src/pages/bookmark/BookmarkPage.tsx
Labels: 기능구현

#85 [feat/#84] 설정 페이지 디자인 수정
  src/pages/setting/darktheme.tsx
  src/pages/setting/settingpage.tsx
  src/pages/start.tsx
Labels: 디자인

#86 [Feat/#82] 클립보드 페이지 디자인 수정
  src/components/ClipBookmarkDropdown.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/clipboard/clipboardpage.tsx
Labels: 디자인, 기능구현

#89 [chore/#88] 베이스 도메인 설정 변경
  src/components/ClipBookmarkDropdown.tsx
  src/components/DragNDrop.tsx
  src/components/SigninModal.tsx
  src/components/SignupModal.tsx
  src/domain/domain.ts
  src/pages/alarm/alarmpage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/ClipboardAPI.tsx
  src/pages/setting/SettingAPI.tsx
Labels: 환경설정

#91 [feat/#87] 전반적인 테마적용
  src/Panel.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/pages/setting/darktheme.tsx
  src/pages/setting/settingpage.tsx
  src/pages/start.tsx
  tailwind.config.js
Labels: 디자인

#93 [Feat/#92] 알람 페이지 디자인 개선
  src/domain/domain.ts
  src/pages/alarm/alarmpage.tsx
Labels: 디자인

#95 [Feat/#94] 설정페이지 디자인
  src/pages/alarm/alarmpage.tsx
  src/pages/setting/settingpage.tsx
Labels: 디자인

#97 [feat/#90] 로그인 상태에 따른 조건부 랜더링 + 회원가입 모달 위치 변경
  src/Panel.tsx
  src/components/SignupModal.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/setting/settingpage.tsx
Labels: 이슈해결, 기능구현

#98 [Feat/#96] 북마크 디자인수정
  src/components/DragNDrop.tsx
  src/components/bookmark/NewBookmarkModal.tsx
  src/components/bookmark/NewFolderModal.tsx
  src/pages/alarm/alarmpage.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/pages/setting/settingpage.tsx
Labels: 디자인

#100 [feat] 북마크 페이지 이미지 첨부
  src/pages/bookmark/BookmarkPage.tsx
Labels: 디자인

#102 [issue] 즐겨찾기 이미지 업데이트 오류 수정
  src/Panel.tsx
  src/components/DragNDrop.tsx
  src/pages/start.tsx
Labels: 이슈해결

#105 [fix/#104] : 로그인 직후 알림 페이지 이동 시 튕기는 오류 수정
  src/Panel.tsx
  src/domain/domain.ts
Labels: 이슈해결

#106 [feat/#103] 다크모드 적용
  src/Panel.tsx
  src/components/Button.tsx
  src/components/ClipBookmarkDropdown.tsx
  src/components/DragNDrop.tsx
  src/components/bookmark/NewBookmarkModal.tsx
  src/components/bookmark/NewFolderModal.tsx
  src/input.css
  src/pages/alarm/alarmpage.tsx
  src/pages/alarm/notificationItem.tsx
  src/pages/bookmark/BookmarkPage.tsx
  src/pages/clipboard/clipboardpage.tsx
  src/pages/setting/darktheme.tsx
  src/pages/setting/settingpage.tsx
  src/pages/start.tsx
  tailwind.config.js
Labels: 디자인

#108 [style] : 북마크 없을때 컴포넌트 이미지 조절
  src/pages/bookmark/BookmarkPage.tsx
Labels: 디자인

#110 [feat] : 다크모드일때 알람메시지 없는 경우 다크모드 적용되지 않은 부분 수정
  src/pages/alarm/alarmpage.tsx
Labels: 디자인
